version: "3"
services:
  bank:
    container_name: 'bank'
    restart: 'always'
    image: bank
    build: ./postgres
    ports:
      - 5490:5432
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
